### ISSUE TITLE
XML / OAI as barrier to participate?

### ISSUE THREAD

**Issue by patrickda** [opencost-de/opencost#20]
I would like to question if OAI /XML is an easy implementation to provide the data. XML is hard to read hard to consume and receiving individual data via OAI is also not fun.  As long there are not easy tool to generate the data I have doubts about XML.

**Comment by bschweighofer** [comment]
The background to the choice of xml is that the project partners use repositories that have mostly established xml as an exchange format in conjunction with OAI-PMH. On the other hand, we didn't want to complicate the discussion by putting two schemas up for disposition.

However, since feedback from the community indicated that openCost would also be useful in a JSON representation, we are working on re-modelling the schema so that it can be serialized in other formats as well. Please check out #63 to find out more about the current status.
